server:
  port: 8009
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: springboot-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    url: jdbc:mysql://localhost:3306/sql_test
    username: root